    var projects = [
      {
        make:      "Toshiba",
        type:      "LCD",
        model:     "22\" LCD TV",
        qr:        "QR",
        smart:     "",
        price:     "1.75",
        icon:      "22AV615.png",
        url:       "product.asp?prodid=VAL22LCD&Category=B"
      },
        make:      "Toshiba",
        type:      "LCD",
        model:     "26\" LCD TV",
        qr:        "QR",
        smart:     "",
        price:     "2.50",
        icon:      "26AV615.png",
        url:       "product.asp?prodid=VAL26LCD&Category=B"
      },
         make:     "Toshiba",
        type:      "LCD",
        model:     "32\" LCD TV",
        qr:        "QR",
        smart:     "",
        price:     "3.00",
        icon:      "32AV615.png",
        url:       "product.asp?prodid=STU32LCD&Category=B"
      },
        make:      "Linsar",
        type:      "LED",
        model:     "32\" 625",
        qr:        "NEW",
        smart:     "Yes",
        price:     "5.75",
        icon:      ".png",
        url:       "product.asp?prodid=VAL32LCD&Category=B"
      },
        make:      "Toshiba",
        type:      "LCD",
        model:     "37\" TV",
        qr:        "QR",
        smart:     "",
        price:     "3.75",
        icon:      "37RV665.png",
        url:       "product.asp?prodid=VAL37LCD&Category=B"
      },
        make:      "Toshiba",
        type:      "LCD",
        model:     "40\" TV",
        qr:        "QR",
        smart:     "",
        price:     "4.75",
        icon:      "40RV635.png",
        url:       ""
      },
        make:      "Panasonic",
        type:      "TV",
        model:     "42\" TV",
        qr:        "NEW",
        smart:     "",
        price:     "5.75",
        icon:      "TX-P42G20.png",
        url:       "product.asp?prodid=VAL42LCD&Category=B"
      },
         make:     "Linsar",
        type:      "LED",
        model:     "42\" 625",
        qr:        "NEW",
        smart:     "Yes",
        price:     "9.50",
        icon:      ".png",
        url:       "product.asp?prodid=STU42LCD&Category=B"
      },
        make:      "Toshiba",
        type:      "LCD",
        model:     "46\" TV",
        qr:        "QR",
        smart:     "",
        price:     "6.75",
        icon:      "46XV635.png",
        url:       ""
      },
        make:      "Panasonic",
        type:      "TV",
        model:     "50\" TV",
        qr:        "QR",
        smart:     "",
        price:     "8.00",
        icon:      "TX-P50G20.png",
        url:       ""
      },
        make:      "Linsar",
        type:      "LED",
        model:     "50\" 625",
        qr:        "",
        smart:     "Yes",
        price:     "11.50",
        icon:      ".png",
        url:       ""
      },
        make:      "Samsung",
        type:      "LED",
        model:     "UE55J5500",
        qr:        "NEW",
        smart:     "Yes",
        price:     "16.50",
        icon:      ".png",
        url:       ""
      },
         make:     "Samsung",
        type:      "Soundbar",
        model:     "HW-J250",
        qr:        "NEW",
        smart:     "",
        price:     "2.50",
        icon:      ".png",
        url:       "product.asp?prodid=SAMHW-J250&Category=I"
      },
        make:      "Egenie",
        type:      "800mm",
        model:     "Glass stand QR",
        qr:        "",
        smart:     "",
        price:     "0.50",
        icon:      "800mm glass STD.png",
        url:       "product.asp?prodid=VALTVSTAND&Category=ZA"
      },
        make:      "Panasonic",
        type:      "",
        model:     "DVD/VCR QR",
        qr:        "QR",
        smart:     "",
        price:     "1.50",
        icon:      "DMR-EZ48.png",
        url:       "product.asp?prodid=PANDMP-BD81&Category=F"
      },
        make:      "Samsung",
        type:      "",
        model:     "Blue Ray QR",
        qr:        "QR",
        smart:     "",
        price:     "1.50",
        icon:      ".png",
        url:       "product.asp?prodid=SAMBDJ5500"
      },
        make:      "Bosch",
        type:      "Washing Machine",
        model:     "1200 6kg",
        smart:     "QR",
        price:     "3.50",
        icon:      "WAA24171.png",
        url:       "product.asp?prodid=VAL12WASHER6&Category=J"
      },
        make:      "Bosch",
        type:      "Washing Machine",
        model:     "1400 6kg",
        qr:        "QR",
        smart:     "",
        price:     "3.75",
        icon:      "WAE28366.png",
        url:       "product.asp?prodid=VAL14WASHER6&Category=J"
      },
        make:      "Bosch",
        type:      "",
        model:     "WAE24062",
        qr:        "NEW",
        smart:     "",
        price:     "4.50",
        icon:      ".png",
        url:       "product.asp?prodid=VAL14WASHER7&Category=J"
      },
        make:      "Bosch",
        type:      "Washing Machine",
        model:     "1400 7kg",
        qr:        "QR",
        smart:     "",
        price:     "4.50",
        icon:      "WAE28467.png",
        url:       "product.asp?prodid=VAL14WASHER7&Category=J"
      },
        make:      "Bosch",
        type:      "Washing Machine",
        model:     "1400 8kg",
        qr:        "QR",
        smart:     "",
        price:     "5.50",
        icon:      "WAQ28461.png",
        url:       "product.asp?prodid=VAL14WASHER8&Category=J"
      },
         make:     "Bosch",
        type:      "8kg",
        model:     "WAQ283S1",
        qr:        "NEW",
        smart:     "",
        price:     "6.25",
        icon:      ".png",
        url:       "product.asp?prodid=VAL14WASHER8&Category=J"
      },
        make:      "Bosch",
        type:      "Dishwasher",
        model:     "60cm",
        qr:        "QR",
        smart:     "",
        price:     "3.75",
        icon:      ".png",
        url:       "product.asp?prodid=VALDW9&Category=K"
      },
         make:     "Bosch",
        type:      "Tumble Dryer",
        model:     "Vented",
        qr:        "QR",
        smart:     "",
        price:     "3.00",
        icon:      "WTV74105.png",
        url:       ""
      },
        make:      "Bosch",
        type:      "Tumble Dryer",
        model:     "Condensor",
        qr:        "QR",
        smart:     "",
        price:     "4.25",
        icon:      "WTE84105.png",
        url:       "product.asp?prodid=VALDRYERVENT"
      },
         make:     "Bosch",
        type:      "Fridge Freezer",
        model:     "QR",
        smart:     "",
        price:     "4.50",
        icon:      "KGV28V01.png",
        url:       "product.asp?prodid=VALFREEZER&Category=L"
      },
        make:      "Bosch",
        type:      "Fridge",
        model:     "Under Counter",
        qr:        "QR",
        smart:     "",
        price:     "3.25",
        icon:      "UR584.png",
        url:       "product.asp?prodid=VALFRIDGE&Category=L"
      },
        make:      "Bosch",
        type:      "Freezer",
        model:     "Under Counter",
        qr:        "QR",
        smart:     "",
        price:     "3.25",
        icon:      "UF584.png",
        url:       "product.asp?prodid=VALFREEZER&Category=L"
      },
        make:      "Beko",
        type:      "Cooker",
        model:     "Electric 50cm",
        qr:        "QR",
        smart:     "",
        price:     "4.50",
        icon:      "BDVC563.png",
        url:       "product.asp?prodid=BEKBDVC563AW&Category=ZZ"
      },
        make:      "Beko",
        type:      "Cooker",
        model:     "Electric 50cm",
        qr:        "QR",
        smart:     "",
        price:     "3.50",
        icon:      "BD531 * no fan.png",
        url:       "product.asp?prodid=BEKBD531AW"
      },
         make:     "Panasonic",
        type:      "Microwave",
        model:     "QR",
        qr:        "",
        smart:     "",
        price:     "1.00",
        icon:      "NN-E289MMBPQ.png",
        url:       "product.asp?prodid=PANNN-E281M&Category=ZZ"
      },
        make:      "Panasonic",
        type:      "Vacuum",
        model:     "",
        qr:        "QR",
        smart:     "",
        price:     "2.00",
        icon:      "MC-UL592WP47.png",
        url:       ""
      }
    ];